### ISSUE TITLE
[Bug] Task list (`- [ ]`) escaped to `\[ \]` when switching to Rich Text mode

### ISSUE THREAD

**Issue by ylang-ylang** [BaldissaraMatheus/Tasks.md#183]
Hello! When I write a task list like `- [ ] todo1` in `task.md` and switch to Rich Text mode, the syntax is automatically escaped to `- \[ \] todo1`, breaking the task list.

**Steps to Reproduce**

1. Add the following in a Markdown file (e.g., `task.md`):

   ```markdown
   - [ ] todo
   - [x] done
   ```
2. Toggle to Rich Text/WYSIWYG mode.
3. Toggle back to Markdown or save the file.
4. Observe: the above lines become:

   ```markdown
   - \[ \] todo
   - \[x\] done
   ```

**Expected Behavior**
The task list syntax (`- [ ]`, `- [x]`) should **remain intact** when switching modes. The editor should recognize task list items and **not escape the brackets**.

**Possible Reason & Suggestion**
It seems the editor’s Markdown handling doesn’t support task-list syntax (GFM). As a result, `[` and `]` are being treated as plain characters that need escaping. It would help to enable GFM / task list support in both Markdown parsing and serialization.

**Thanks for your great work on `task.md`!**
I’d appreciate it if this could be addressed, as it would improve the WYSIWYG experience significantly.

**Comment by ylang-ylang** [comment]
Sorry, I found that it has already been resolved in 3.0.

**Comment by benjaminapetersen** [comment]
@ylang-ylang I don't have perms to re-open the issue. Do you? Or i can recreate.

**Comment by BaldissaraMatheus** [comment]
@benjaminapetersen Hmm maybe it's a cache issue, idk. I suggest two alternatives:
- Check if it works on a incognito window
- Create a new container on a different directory and port 

When you're available could you try those and see if it works?

Also there is no button in the toolbar to create task items right now, you can only do that with "- [ ] text" syntax (should work on both editor modes)

**Comment by benjaminapetersen** [comment]
Can do!

**Comment by oneills24** [comment]
Hello, I also have a similar issue. To solve this issue, I did the following above recommended by @BaldissaraMatheus 

    Check if it works on a incognito window
    Create a new container on a different directory and port

The issue still happens to me. 

<img width="971" height="214" alt="Image" src="https://github.com/user-attachments/assets/783cf8b0-8ca6-4501-a157-735d06ae8496" />

<img width="929" height="171" alt="Image" src="https://github.com/user-attachments/assets/d5d93091-325a-4fc1-91e7-73bc2d667ad4" />

Although, this did not happen when I switched from Rich Text mode to Markdown (or vice versa). This happens when I close and reopen the file. Either from Rich Text or Markdown.

**Comment by oneills24** [comment]
Update: I have confirmed this is only happening on release 3.1

Release 3.0.9 does not have these issues for me

**Comment by BaldissaraMatheus** [comment]
Hey @oneills24 I just published a new release with an update to dockerhub, could you check if it's fixed now?
